#!/usr/bin/env bash
# Script that transfers files from client to server

# PATH_TO_FILE=$1
# IP=$2
# USERNAME=$3
# PATH_TO_SSH_KEY=$4

if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi

