#!/usr/bin/env bash
# Configure Nginx so its HTTP response contains
# custom header

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 26071-web-01 54.158.205.135:80 check
    server 26071-web-02 18.233.67.97:80 check
"
# Updates packages
apt-get -y update
apt-get -y upgrade

# Adds HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Installs HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
