#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Define actions to take for corresponding signal handlers
trap "echo I hate the kill command ; rm /var/run/myscript.pid ; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "/var/run/myscript.pid ; exit" SIGQUIT

# Creates file cntaining its PID
ps | pgrep bash | head -n 1 | awk '{print $1}' > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
