#!/usr/bin/env bash
# Displays "bad luck" at the 4th
# "good luck" at the 8th
# "Best School" for others of the while loop

p=0

while [ $p -lt 10 ]
do
	if [ $p -eq 3 ]
	then
		echo "bad luck"
	elif [ $p -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((p++))
done	
